version: "3.8"

services:
    postgres:
        image: postgres:15-alpine3.16
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .env
        ports:
            - "7474:5432"

    api:
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        image: jasurbe/telegrambot:latest
        ports:
            - "8080:8080"
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        depends_on:
            - postgres
            
        restart: always

volumes:
    pgdata: