CREATE TABLE "openbudjet" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chat_id" bigint,
  "phone" integer,
  "full_name" text,
  "last_name" text,
  "status" integer,
  "type" integer,
  "time" integer
);

CREATE TABLE "user_check" (
  "chat_id" bigint,
  "phone" integer,
  "key" text,
  "optkey" text
);

CREATE TABLE "users_data" (
  "chat_id" bigint,
  "time" text,
  "amount" integer
);

CREATE TABLE "token_check" (
  "key" integer,
  "token" text
);  

CREATE TABLE "users_payment" (
  "chat_id" bigint,
  "phone" integer,
  "full_name" text,
  "price" integer,
  "time" text
);

CREATE TABLE "users_openbudjet" (
  "chat_id" bigint,
  "phone" integer,
  "full_name" text,
  "time" text
);
